src/objects/Inspection__c.object
<CustomObject>
    <fields>
        <fullName>InspectionDateTime__c</fullName>
        <label>点検日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Worker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>点検者</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Equipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>点検予実</label>
    <nameField>
        <displayFormat>点検-{0000}</displayFormat>
        <label>点検番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EventLogic.cls
public class EventLogic {

    public static void UpdateInspectionWorkerDateTime(List<Event> evList){
        System.debug('@@@ UpdateInspectionWorkerDateTime()');
        Set<Id> inspectionIdSet = new Set<Id>();
        for(Event ev :evList){
            inspectionIdSet.add(ev.WhatId);
        }
        for(Inspection__c ip :[SELECT Id, InspectionDateTime__c, Worker__c FROM Inspection__c WHERE Id = :inspectionIdSet]){
            for(Event ev :evList){
                if(ev.WhatId == ip.Id){
                    System.debug('***ev ' + ev);
                    System.debug('***ip ' + ip);
                    QueueableUpdateInspection queueableUpdateInspection = new QueueableUpdateInspection(ev, ip);
                    System.enqueueJob(queueableUpdateInspection);
                }
            }
        }
    }

    public class QueueableUpdateInspection implements System.Queueable {
        private Event ev;
        private Inspection__c ip;
        public QueueableUpdateInspection(Event ev, Inspection__c ip){
            System.debug('@@@ QueueableUpdateInspection()');
            this.ev = ev;
            this.ip = ip;
        }
        public void execute(QueueableContext context) {
            ip.Worker__c = ev.OwnerId;
            ip.InspectionDateTime__c = ev.StartDateTime;
            update ip;
            System.debug('***ev(Q) ' + ev);
            System.debug('***ip(Q) ' + ip);
        }
    }

}